### ISSUE TITLE
第1回 6/4 20:00〜

### ISSUE THREAD

**Issue by nappan23** [nakano-rb/principle_of_programming_book_reading#1]
プロローグから

**Comment by nappan23** [comment]
知識の素通り、場当たり的な対応になってしまう

**Comment by nappan23** [comment]
https://twitter.com/t_wada/status/904916106153828352

**Comment by nappan23** [comment]
https://twitter.com/a_matsuda/status/1077817201158062080

**Comment by nappan23** [comment]
偶有的とは
それがなくてもソフトウェアが成り立つもの
ライブラリ・フレームワークなどは別のものを選んでも目的を果たすことはできるので
自動化して本質にできるだけ取り組む

本質＝ソフトウェアの提供したい価値そのもの

**Comment by mistyrinth** [comment]
偶有的の例：ビルド環境、プログラミング言語、ライブラリ、フレームワークなど
→あれば自動化して本質的なところに注力する

**Comment by nappan23** [comment]
次回 6/5 20:00~
1章を終わらせる

**Comment by rin0801** [comment]
## 思ったこと
- ３年目とか５年目あたりで１回読みたかったなあ
- 自分のことエンジニアって紹介してたかも・・言葉の定義って大事
- もっと実践的な技術書読まなきゃってなってたけど、この本読んでからの方が学習の土台ができる気がした
- 身近なものの例えとかがあって読みやすいし印象に残る
- 言語に左右されずみんなが共通認識として持つべきことがたくさん書いてあるなと思った

**Comment by nappan23** [comment]
# K
- 祝読書会開催 🎉 
- さやかちゃんがいい時期にこの本を読んでいる 👍 
- ソフトウェアには本質と偶有的な部分があり、偶有的な部分にはできるだけ時間をかけず、本質に時間を掛けることが大事というのがわかった。
- 和田さんの「コメントに何を書くべきか」ツイートを改めて読んで、うろ覚えしていたのであらためて勉強になった
=> コメントに「Why」を書いちゃっていて、「Why not」を書けてなかったなあ…と思った
- 言葉の定義がされててめっちゃ丁寧

# P
- プロローグはそれぞれ事前に読んでおいても良かったかも？

# T
- 人月の神話、読んでなかった。いつか読むか…
- Notion試してみたい

**Comment by mistyrinth** [comment]
# 読書会の感想
- ペースが速すぎず、ついていきやすくて良かったです。
- 朗読するのが非常に久しぶりで、漢字苦手なのでちょっと緊張しました。
- 朗読するの楽しかったです。
- 具体例の少ない本なので、お二人の経験や他の人の発言など教えていただけてあ りがたいです。

# 本の感想
- 最初に各章の内容について説明があったことと、用語が定義されているのが読みやすくて親切だと思いました。

**Comment by nappan23** [comment]
https://www.notion.so/14316ba2eb704f0889567a50a3199f73

**Comment by nappan23** [comment]
https://seleck.cc/kpt

**Comment by mistyrinth** [comment]
・Keep：うまくいったことを確認する
・Problem：問題を洗い出す、原因を分析する、改善策を考える
・Try：試したいことを考える、試すことを選ぶ

**Comment by nappan23** [comment]
以降はNotionで
https://www.notion.so/9f763cf477334149ae3af77e08e37fa2
